name: Build Rublox
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          version: "13.1.0"   # проверенная стабильная версия

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -G "MinGW Makefiles"
          mingw32-make

      - name: Prepare final package
        shell: cmd
        run: |
          mkdir Rublox
          copy build\Rublox.exe Rublox\ 2>nul || copy build\Debug\Rublox.exe Rublox\ || copy build\Release\Rublox.exe Rublox\
          copy menu.lua Rublox\
          xcopy /E /I Games Rublox\Games
          copy "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin\*.dll" Rublox\

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rublox
          path: Rublox\
